### ISSUE TITLE
Social integration on post when not authenticated with services.

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#102]
![image](https://cloud.githubusercontent.com/assets/3341822/24314180/c42c45a6-10b6-11e7-84d7-199329ac838f.png)

See image: I am not authenticated with twitter.

Either:
- the twitter button should be hidden
- the twitter button should prompt me to sign in with twitter as well
    - NOTE: this requires a bunch of auth flow changes and we may need to pay auth0 for this feature

**Comment by ericljpemberton** [comment]
It looks like the visibility of the Facebook and Twitter Buttons are enabled based on the preferences.

I have added a check to the identities array in the user's profile (AuthService.getProfile().identity to check if any of the connections in the array match facebook or twitter

```
    const integrations = AuthService.getProfile().identities;
    for (let integration of integrations) {
      if (integration.connection === 'facebook') {
        fbIntegration = true;
      } else if (integration.connection === 'twitter') {
        twIntegration = true;
      }
    }
```
Is this the correct assumption that if we were to store multiple identities they would be located here?

**Comment by kyl191** [comment]
Based on the auth0 docs, yes.

**Comment by ericljpemberton** [comment]
@kyl191 I'm going to close this now as it should be resolved with the recent merge of my PR
