### ISSUE TITLE
Social links should be centered on profile page

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#105]
We only support one social integration per user, so we should probably center it. Note: each user has exactly one social integration (facebook xor twitter).

![image](https://cloud.githubusercontent.com/assets/3341822/24314371/9ece7f12-10b7-11e7-890f-d70f56241567.png)

**Comment by TheKevJames** [comment]
Huh, looks like there's a "Link Another Account" button hidden there, rendered white, that I didn't notice at first. That should be removed, since we don't support linking other accounts.

**Comment by schneider-clarisse** [comment]
@TheKevJames .... we do support linking other accounts.

**Comment by schneider-clarisse** [comment]
Unfortunately it appears that the twitter/facebook objects on a person's profile is never populated from the linking of accounts. I'll just do it a different way (i :'( because i spent so much time on linking accounts...... but whatever i'm over it)
