### ISSUE TITLE
Preferences page is confusing to use

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#109]
I assume this just hasn't been styled yet.

![image](https://cloud.githubusercontent.com/assets/3341822/24314839/192a14f4-10ba-11e7-8834-e6007d3a127e.png)

Also, "Faceboox" is typo'ed.

**Comment by larajanecka** [comment]
I think you're already on this so im assigning you just so you can close it and feel that sweet sweet satisfaction.
