### ISSUE TITLE
Users are not created

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#112]
After a 404 is received on looking up a user, no new user is created. This is some sort of regression, I think.

**Comment by StevenLocke** [comment]
Related to [AuthService.jsx](https://github.com/Calligre/attendee-web/blob/master/src/js/util/AuthService.jsx#L71) I think it's because the `this` is now messed up from scoping issues.  Potentially fixed with jquery removal?
@larajanecka

**Comment by larajanecka** [comment]
No idea. When you put a break point there and inspect it is this.getCurrentUserId defined?

**Comment by TheKevJames** [comment]
No, its not. Steven thinks the `this` is not _this_ `this`... or something, I don't know what's going on with this `this`. Someone please help me.

**Comment by StevenLocke** [comment]
Easiest fix in the world.
Change:
`const userData = {
          id: this.getCurrentUserId(),
          ...
`
To:
`const userData = {
          id: id,
          ...
`
