### ISSUE TITLE
Integrate news feed with Facebook and Twitter

### ISSUE THREAD

**Issue by ericljpemberton** [Calligre/attendee-web#22]
When we post we also need to be able to send this to Facebook or Twitter with the user's credentials (also need to check if they have these configured)

**Comment by TheKevJames** [comment]
Is this done?

**Comment by ericljpemberton** [comment]
@kyl191 I thought this was done. We were able to post a while ago and it seems like I'm still passing you the proper flag. Is it currently disabled on the backend?

**Comment by ericljpemberton** [comment]
Closed as working
