### ISSUE TITLE
Get user info from auth0 instead of our API wherever possible

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#43]
Things like `first_name`, `last_name`, `email`, `facebook`, `twitter`, and `linkedin` are already stored in Auth0, so we shouldn't store them ourselves.

**Comment by kyl191** [comment]
We need to keep a name <-> id mapping around to populate the social stuff. The `first_name` & `last_name` stuff can get dumped in favour of the `name` parameter from auth0.

Currently posts only have the uid of the creator, and the uid of the likers. Liking can't really be done without uids, names will eventually collide.

We don't have to keep this in the current database, but I think it makes the most sense so we don't have to spin up a Redis instance/other key/value store.

**Comment by kyl191** [comment]
Follow-up: It makes sense to keep local copies of stuff around so we don't have to fetch from Auth0 every time a page loads. 
Also, support things like getting other users' profiles.
Selectively disabling the "post to Twitter/FB" checkboxes depending on what accounts the user has linked.
